-- Seed data for the lab4 cache-vs-no-cache demo.
-- Invented product catalog data, executed by the Lambda function on cold
-- start (idempotent) and once explicitly by Terraform right after deploy.

CREATE TABLE IF NOT EXISTS items (
    id          INTEGER PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT NOT NULL,
    price       NUMERIC(10, 2) NOT NULL
);

INSERT INTO items (id, name, description, price) VALUES
(1, 'Ergonomic Backpack', 'Ergonomic Backpack crafted from carbon fiber, item #1 in the catalog. Designed for everyday use with a focus on durability and comfort.', 126.21),
(2, 'Portable Wall Clock', 'Portable Wall Clock crafted from recycled polyester, item #2 in the catalog. Designed for everyday use with a focus on durability and comfort.', 339.96),
(3, 'Modular Desk Lamp', 'Modular Desk Lamp crafted from genuine leather, item #3 in the catalog. Designed for everyday use with a focus on durability and comfort.', 213.84),
(4, 'Rugged Desk Lamp', 'Rugged Desk Lamp crafted from bamboo, item #4 in the catalog. Designed for everyday use with a focus on durability and comfort.', 120.16),
(5, 'Reinforced Backpack', 'Reinforced Backpack crafted from ABS plastic, item #5 in the catalog. Designed for everyday use with a focus on durability and comfort.', 103.41),
(6, 'Modular Phone Case', 'Modular Phone Case crafted from bamboo, item #6 in the catalog. Designed for everyday use with a focus on durability and comfort.', 227.35),
(7, 'Heavy-Duty Blender', 'Heavy-Duty Blender crafted from aluminum, item #7 in the catalog. Designed for everyday use with a focus on durability and comfort.', 380.6),
(8, 'Premium Sunglasses', 'Premium Sunglasses crafted from tempered glass, item #8 in the catalog. Designed for everyday use with a focus on durability and comfort.', 173.41),
(9, 'Portable Monitor Stand', 'Portable Monitor Stand crafted from organic cotton, item #9 in the catalog. Designed for everyday use with a focus on durability and comfort.', 55.58),
(10, 'Waterproof Bluetooth Speaker', 'Waterproof Bluetooth Speaker crafted from organic cotton, item #10 in the catalog. Designed for everyday use with a focus on durability and comfort.', 424.5),
(11, 'Reinforced Running Shoes', 'Reinforced Running Shoes crafted from aluminum, item #11 in the catalog. Designed for everyday use with a focus on durability and comfort.', 366.21),
(12, 'Modular Bluetooth Speaker', 'Modular Bluetooth Speaker crafted from tempered glass, item #12 in the catalog. Designed for everyday use with a focus on durability and comfort.', 44.0),
(13, 'Lightweight Umbrella', 'Lightweight Umbrella crafted from genuine leather, item #13 in the catalog. Designed for everyday use with a focus on durability and comfort.', 443.29),
(14, 'Foldable Garden Hose', 'Foldable Garden Hose crafted from bamboo, item #14 in the catalog. Designed for everyday use with a focus on durability and comfort.', 353.75),
(15, 'Compact Hiking Boots', 'Compact Hiking Boots crafted from bamboo, item #15 in the catalog. Designed for everyday use with a focus on durability and comfort.', 387.66),
(16, 'Wireless Wallet', 'Wireless Wallet crafted from bamboo, item #16 in the catalog. Designed for everyday use with a focus on durability and comfort.', 433.9),
(17, 'Waterproof Running Shoes', 'Waterproof Running Shoes crafted from high-density foam, item #17 in the catalog. Designed for everyday use with a focus on durability and comfort.', 319.65),
(18, 'Foldable Keyboard', 'Foldable Keyboard crafted from organic cotton, item #18 in the catalog. Designed for everyday use with a focus on durability and comfort.', 180.85),
(19, 'Heavy-Duty Sunglasses', 'Heavy-Duty Sunglasses crafted from recycled polyester, item #19 in the catalog. Designed for everyday use with a focus on durability and comfort.', 306.51),
(20, 'Premium Backup Camera', 'Premium Backup Camera crafted from bamboo, item #20 in the catalog. Designed for everyday use with a focus on durability and comfort.', 85.87),
(21, 'Waterproof Running Shoes', 'Waterproof Running Shoes crafted from ABS plastic, item #21 in the catalog. Designed for everyday use with a focus on durability and comfort.', 113.7),
(22, 'Adjustable Umbrella', 'Adjustable Umbrella crafted from aluminum, item #22 in the catalog. Designed for everyday use with a focus on durability and comfort.', 118.37),
(23, 'Compact Blender', 'Compact Blender crafted from organic cotton, item #23 in the catalog. Designed for everyday use with a focus on durability and comfort.', 203.57),
(24, 'Wireless Monitor Stand', 'Wireless Monitor Stand crafted from genuine leather, item #24 in the catalog. Designed for everyday use with a focus on durability and comfort.', 438.79),
(25, 'Adjustable Monitor Stand', 'Adjustable Monitor Stand crafted from high-density foam, item #25 in the catalog. Designed for everyday use with a focus on durability and comfort.', 200.83),
(26, 'Industrial Office Chair', 'Industrial Office Chair crafted from carbon fiber, item #26 in the catalog. Designed for everyday use with a focus on durability and comfort.', 74.11),
(27, 'Modular Backup Camera', 'Modular Backup Camera crafted from carbon fiber, item #27 in the catalog. Designed for everyday use with a focus on durability and comfort.', 374.76),
(28, 'Cordless Travel Pillow', 'Cordless Travel Pillow crafted from genuine leather, item #28 in the catalog. Designed for everyday use with a focus on durability and comfort.', 202.69),
(29, 'Smart Office Chair', 'Smart Office Chair crafted from ABS plastic, item #29 in the catalog. Designed for everyday use with a focus on durability and comfort.', 249.28),
(30, 'Compact Wallet', 'Compact Wallet crafted from recycled polyester, item #30 in the catalog. Designed for everyday use with a focus on durability and comfort.', 80.65),
(31, 'Premium Blender', 'Premium Blender crafted from tempered glass, item #31 in the catalog. Designed for everyday use with a focus on durability and comfort.', 300.21),
(32, 'Waterproof Bike Helmet', 'Waterproof Bike Helmet crafted from genuine leather, item #32 in the catalog. Designed for everyday use with a focus on durability and comfort.', 498.07),
(33, 'Modern Running Shoes', 'Modern Running Shoes crafted from ABS plastic, item #33 in the catalog. Designed for everyday use with a focus on durability and comfort.', 431.08),
(34, 'Rugged Hiking Boots', 'Rugged Hiking Boots crafted from recycled polyester, item #34 in the catalog. Designed for everyday use with a focus on durability and comfort.', 342.44),
(35, 'Modular Cutting Board', 'Modular Cutting Board crafted from carbon fiber, item #35 in the catalog. Designed for everyday use with a focus on durability and comfort.', 385.45),
(36, 'Adjustable Bluetooth Speaker', 'Adjustable Bluetooth Speaker crafted from carbon fiber, item #36 in the catalog. Designed for everyday use with a focus on durability and comfort.', 220.2),
(37, 'Industrial Backpack', 'Industrial Backpack crafted from carbon fiber, item #37 in the catalog. Designed for everyday use with a focus on durability and comfort.', 486.07),
(38, 'Premium Headphones', 'Premium Headphones crafted from recycled polyester, item #38 in the catalog. Designed for everyday use with a focus on durability and comfort.', 435.9),
(39, 'Lightweight Umbrella', 'Lightweight Umbrella crafted from ABS plastic, item #39 in the catalog. Designed for everyday use with a focus on durability and comfort.', 306.43),
(40, 'Portable Camping Tent', 'Portable Camping Tent crafted from stainless steel, item #40 in the catalog. Designed for everyday use with a focus on durability and comfort.', 271.98),
(41, 'Modern Laptop Sleeve', 'Modern Laptop Sleeve crafted from aluminum, item #41 in the catalog. Designed for everyday use with a focus on durability and comfort.', 301.47),
(42, 'Vintage Backpack', 'Vintage Backpack crafted from recycled polyester, item #42 in the catalog. Designed for everyday use with a focus on durability and comfort.', 464.89),
(43, 'Lightweight Coffee Mug', 'Lightweight Coffee Mug crafted from aluminum, item #43 in the catalog. Designed for everyday use with a focus on durability and comfort.', 124.22),
(44, 'Insulated Desk Lamp', 'Insulated Desk Lamp crafted from recycled polyester, item #44 in the catalog. Designed for everyday use with a focus on durability and comfort.', 367.28),
(45, 'Wireless Cutting Board', 'Wireless Cutting Board crafted from ABS plastic, item #45 in the catalog. Designed for everyday use with a focus on durability and comfort.', 384.08),
(46, 'Portable Hiking Boots', 'Portable Hiking Boots crafted from high-density foam, item #46 in the catalog. Designed for everyday use with a focus on durability and comfort.', 473.68),
(47, 'Premium Running Shoes', 'Premium Running Shoes crafted from ABS plastic, item #47 in the catalog. Designed for everyday use with a focus on durability and comfort.', 436.84),
(48, 'Cordless Monitor Stand', 'Cordless Monitor Stand crafted from ABS plastic, item #48 in the catalog. Designed for everyday use with a focus on durability and comfort.', 378.85),
(49, 'Eco-Friendly Sunglasses', 'Eco-Friendly Sunglasses crafted from carbon fiber, item #49 in the catalog. Designed for everyday use with a focus on durability and comfort.', 202.49),
(50, 'Foldable Power Bank', 'Foldable Power Bank crafted from ABS plastic, item #50 in the catalog. Designed for everyday use with a focus on durability and comfort.', 228.48),
(51, 'Smart Coffee Mug', 'Smart Coffee Mug crafted from recycled polyester, item #51 in the catalog. Designed for everyday use with a focus on durability and comfort.', 172.34),
(52, 'Insulated Backup Camera', 'Insulated Backup Camera crafted from bamboo, item #52 in the catalog. Designed for everyday use with a focus on durability and comfort.', 296.27),
(53, 'Rugged Desk Lamp', 'Rugged Desk Lamp crafted from aluminum, item #53 in the catalog. Designed for everyday use with a focus on durability and comfort.', 118.32),
(54, 'Compact Wallet', 'Compact Wallet crafted from organic cotton, item #54 in the catalog. Designed for everyday use with a focus on durability and comfort.', 40.06),
(55, 'Smart Running Shoes', 'Smart Running Shoes crafted from high-density foam, item #55 in the catalog. Designed for everyday use with a focus on durability and comfort.', 111.04),
(56, 'Portable Wall Clock', 'Portable Wall Clock crafted from genuine leather, item #56 in the catalog. Designed for everyday use with a focus on durability and comfort.', 290.21),
(57, 'Smart Blender', 'Smart Blender crafted from high-density foam, item #57 in the catalog. Designed for everyday use with a focus on durability and comfort.', 404.7),
(58, 'Eco-Friendly Bluetooth Speaker', 'Eco-Friendly Bluetooth Speaker crafted from recycled polyester, item #58 in the catalog. Designed for everyday use with a focus on durability and comfort.', 331.19),
(59, 'Foldable Phone Case', 'Foldable Phone Case crafted from tempered glass, item #59 in the catalog. Designed for everyday use with a focus on durability and comfort.', 236.17),
(60, 'Compact Hiking Boots', 'Compact Hiking Boots crafted from recycled polyester, item #60 in the catalog. Designed for everyday use with a focus on durability and comfort.', 34.99),
(61, 'Adjustable Blender', 'Adjustable Blender crafted from recycled polyester, item #61 in the catalog. Designed for everyday use with a focus on durability and comfort.', 128.07),
(62, 'Eco-Friendly Backup Camera', 'Eco-Friendly Backup Camera crafted from high-density foam, item #62 in the catalog. Designed for everyday use with a focus on durability and comfort.', 74.38),
(63, 'Premium Running Shoes', 'Premium Running Shoes crafted from high-density foam, item #63 in the catalog. Designed for everyday use with a focus on durability and comfort.', 128.64),
(64, 'Wireless Power Bank', 'Wireless Power Bank crafted from ABS plastic, item #64 in the catalog. Designed for everyday use with a focus on durability and comfort.', 53.45),
(65, 'Modular Umbrella', 'Modular Umbrella crafted from aluminum, item #65 in the catalog. Designed for everyday use with a focus on durability and comfort.', 484.64),
(66, 'Smart Keyboard', 'Smart Keyboard crafted from tempered glass, item #66 in the catalog. Designed for everyday use with a focus on durability and comfort.', 245.38),
(67, 'Eco-Friendly Wallet', 'Eco-Friendly Wallet crafted from tempered glass, item #67 in the catalog. Designed for everyday use with a focus on durability and comfort.', 451.7),
(68, 'Premium Bike Helmet', 'Premium Bike Helmet crafted from aluminum, item #68 in the catalog. Designed for everyday use with a focus on durability and comfort.', 492.72),
(69, 'Heavy-Duty Laptop Sleeve', 'Heavy-Duty Laptop Sleeve crafted from high-density foam, item #69 in the catalog. Designed for everyday use with a focus on durability and comfort.', 146.19),
(70, 'Modular Hiking Boots', 'Modular Hiking Boots crafted from high-density foam, item #70 in the catalog. Designed for everyday use with a focus on durability and comfort.', 81.61),
(71, 'Lightweight Monitor Stand', 'Lightweight Monitor Stand crafted from aluminum, item #71 in the catalog. Designed for everyday use with a focus on durability and comfort.', 291.68),
(72, 'Modular Water Bottle', 'Modular Water Bottle crafted from organic cotton, item #72 in the catalog. Designed for everyday use with a focus on durability and comfort.', 33.29),
(73, 'Insulated Notebook', 'Insulated Notebook crafted from ABS plastic, item #73 in the catalog. Designed for everyday use with a focus on durability and comfort.', 460.09),
(74, 'Modern Keyboard', 'Modern Keyboard crafted from aluminum, item #74 in the catalog. Designed for everyday use with a focus on durability and comfort.', 480.58),
(75, 'Wireless Wallet', 'Wireless Wallet crafted from stainless steel, item #75 in the catalog. Designed for everyday use with a focus on durability and comfort.', 38.91),
(76, 'Wireless Hiking Boots', 'Wireless Hiking Boots crafted from bamboo, item #76 in the catalog. Designed for everyday use with a focus on durability and comfort.', 204.86),
(77, 'Insulated Coffee Mug', 'Insulated Coffee Mug crafted from genuine leather, item #77 in the catalog. Designed for everyday use with a focus on durability and comfort.', 299.28),
(78, 'Reinforced Desk Lamp', 'Reinforced Desk Lamp crafted from tempered glass, item #78 in the catalog. Designed for everyday use with a focus on durability and comfort.', 330.39),
(79, 'Insulated Headphones', 'Insulated Headphones crafted from organic cotton, item #79 in the catalog. Designed for everyday use with a focus on durability and comfort.', 467.67),
(80, 'Eco-Friendly Hiking Boots', 'Eco-Friendly Hiking Boots crafted from organic cotton, item #80 in the catalog. Designed for everyday use with a focus on durability and comfort.', 123.14),
(81, 'Waterproof Office Chair', 'Waterproof Office Chair crafted from carbon fiber, item #81 in the catalog. Designed for everyday use with a focus on durability and comfort.', 231.32),
(82, 'Wireless Backpack', 'Wireless Backpack crafted from high-density foam, item #82 in the catalog. Designed for everyday use with a focus on durability and comfort.', 312.46),
(83, 'Insulated Bluetooth Speaker', 'Insulated Bluetooth Speaker crafted from recycled polyester, item #83 in the catalog. Designed for everyday use with a focus on durability and comfort.', 271.12),
(84, 'Modern Running Shoes', 'Modern Running Shoes crafted from stainless steel, item #84 in the catalog. Designed for everyday use with a focus on durability and comfort.', 466.95),
(85, 'Wireless Travel Pillow', 'Wireless Travel Pillow crafted from bamboo, item #85 in the catalog. Designed for everyday use with a focus on durability and comfort.', 187.91),
(86, 'Premium Power Bank', 'Premium Power Bank crafted from ABS plastic, item #86 in the catalog. Designed for everyday use with a focus on durability and comfort.', 353.24),
(87, 'Reinforced Blender', 'Reinforced Blender crafted from ABS plastic, item #87 in the catalog. Designed for everyday use with a focus on durability and comfort.', 8.86),
(88, 'Modular Yoga Mat', 'Modular Yoga Mat crafted from recycled polyester, item #88 in the catalog. Designed for everyday use with a focus on durability and comfort.', 469.76),
(89, 'Portable Running Shoes', 'Portable Running Shoes crafted from recycled polyester, item #89 in the catalog. Designed for everyday use with a focus on durability and comfort.', 445.4),
(90, 'Modular Office Chair', 'Modular Office Chair crafted from carbon fiber, item #90 in the catalog. Designed for everyday use with a focus on durability and comfort.', 144.46),
(91, 'Eco-Friendly Sunglasses', 'Eco-Friendly Sunglasses crafted from organic cotton, item #91 in the catalog. Designed for everyday use with a focus on durability and comfort.', 105.77),
(92, 'Heavy-Duty Headphones', 'Heavy-Duty Headphones crafted from high-density foam, item #92 in the catalog. Designed for everyday use with a focus on durability and comfort.', 129.3),
(93, 'Compact Desk Lamp', 'Compact Desk Lamp crafted from tempered glass, item #93 in the catalog. Designed for everyday use with a focus on durability and comfort.', 415.52),
(94, 'Compact Backpack', 'Compact Backpack crafted from organic cotton, item #94 in the catalog. Designed for everyday use with a focus on durability and comfort.', 386.69),
(95, 'Heavy-Duty Keyboard', 'Heavy-Duty Keyboard crafted from high-density foam, item #95 in the catalog. Designed for everyday use with a focus on durability and comfort.', 278.07),
(96, 'Cordless Backup Camera', 'Cordless Backup Camera crafted from aluminum, item #96 in the catalog. Designed for everyday use with a focus on durability and comfort.', 60.37),
(97, 'Portable Backup Camera', 'Portable Backup Camera crafted from aluminum, item #97 in the catalog. Designed for everyday use with a focus on durability and comfort.', 418.11),
(98, 'Insulated Backup Camera', 'Insulated Backup Camera crafted from stainless steel, item #98 in the catalog. Designed for everyday use with a focus on durability and comfort.', 217.73),
(99, 'Compact Yoga Mat', 'Compact Yoga Mat crafted from organic cotton, item #99 in the catalog. Designed for everyday use with a focus on durability and comfort.', 449.99),
(100, 'Compact Travel Pillow', 'Compact Travel Pillow crafted from organic cotton, item #100 in the catalog. Designed for everyday use with a focus on durability and comfort.', 108.98),
(101, 'Smart Hiking Boots', 'Smart Hiking Boots crafted from recycled polyester, item #101 in the catalog. Designed for everyday use with a focus on durability and comfort.', 180.06),
(102, 'Modular Travel Pillow', 'Modular Travel Pillow crafted from tempered glass, item #102 in the catalog. Designed for everyday use with a focus on durability and comfort.', 487.04),
(103, 'Portable Laptop Sleeve', 'Portable Laptop Sleeve crafted from bamboo, item #103 in the catalog. Designed for everyday use with a focus on durability and comfort.', 432.97),
(104, 'Premium Travel Pillow', 'Premium Travel Pillow crafted from tempered glass, item #104 in the catalog. Designed for everyday use with a focus on durability and comfort.', 17.26),
(105, 'Adjustable Blender', 'Adjustable Blender crafted from tempered glass, item #105 in the catalog. Designed for everyday use with a focus on durability and comfort.', 402.1),
(106, 'Smart Running Shoes', 'Smart Running Shoes crafted from stainless steel, item #106 in the catalog. Designed for everyday use with a focus on durability and comfort.', 394.74),
(107, 'Ergonomic Bike Helmet', 'Ergonomic Bike Helmet crafted from aluminum, item #107 in the catalog. Designed for everyday use with a focus on durability and comfort.', 429.99),
(108, 'Smart Monitor Stand', 'Smart Monitor Stand crafted from high-density foam, item #108 in the catalog. Designed for everyday use with a focus on durability and comfort.', 178.07),
(109, 'Smart Coffee Mug', 'Smart Coffee Mug crafted from aluminum, item #109 in the catalog. Designed for everyday use with a focus on durability and comfort.', 331.71),
(110, 'Waterproof Tool Kit', 'Waterproof Tool Kit crafted from carbon fiber, item #110 in the catalog. Designed for everyday use with a focus on durability and comfort.', 432.84),
(111, 'Heavy-Duty Camping Tent', 'Heavy-Duty Camping Tent crafted from ABS plastic, item #111 in the catalog. Designed for everyday use with a focus on durability and comfort.', 202.83),
(112, 'Modular Tool Kit', 'Modular Tool Kit crafted from aluminum, item #112 in the catalog. Designed for everyday use with a focus on durability and comfort.', 62.08),
(113, 'Heavy-Duty Keyboard', 'Heavy-Duty Keyboard crafted from genuine leather, item #113 in the catalog. Designed for everyday use with a focus on durability and comfort.', 481.44),
(114, 'Heavy-Duty Water Bottle', 'Heavy-Duty Water Bottle crafted from recycled polyester, item #114 in the catalog. Designed for everyday use with a focus on durability and comfort.', 300.29),
(115, 'Foldable Wall Clock', 'Foldable Wall Clock crafted from organic cotton, item #115 in the catalog. Designed for everyday use with a focus on durability and comfort.', 221.0),
(116, 'Modern Bluetooth Speaker', 'Modern Bluetooth Speaker crafted from tempered glass, item #116 in the catalog. Designed for everyday use with a focus on durability and comfort.', 450.24),
(117, 'Eco-Friendly Running Shoes', 'Eco-Friendly Running Shoes crafted from aluminum, item #117 in the catalog. Designed for everyday use with a focus on durability and comfort.', 355.84),
(118, 'Rugged Headphones', 'Rugged Headphones crafted from ABS plastic, item #118 in the catalog. Designed for everyday use with a focus on durability and comfort.', 344.98),
(119, 'Eco-Friendly Camping Tent', 'Eco-Friendly Camping Tent crafted from tempered glass, item #119 in the catalog. Designed for everyday use with a focus on durability and comfort.', 39.63),
(120, 'Adjustable Air Purifier', 'Adjustable Air Purifier crafted from organic cotton, item #120 in the catalog. Designed for everyday use with a focus on durability and comfort.', 333.37),
(121, 'Ergonomic Wall Clock', 'Ergonomic Wall Clock crafted from carbon fiber, item #121 in the catalog. Designed for everyday use with a focus on durability and comfort.', 256.02),
(122, 'Cordless Tool Kit', 'Cordless Tool Kit crafted from tempered glass, item #122 in the catalog. Designed for everyday use with a focus on durability and comfort.', 350.11),
(123, 'Modular Office Chair', 'Modular Office Chair crafted from bamboo, item #123 in the catalog. Designed for everyday use with a focus on durability and comfort.', 213.11),
(124, 'Waterproof Hiking Boots', 'Waterproof Hiking Boots crafted from stainless steel, item #124 in the catalog. Designed for everyday use with a focus on durability and comfort.', 309.67),
(125, 'Lightweight Bike Helmet', 'Lightweight Bike Helmet crafted from ABS plastic, item #125 in the catalog. Designed for everyday use with a focus on durability and comfort.', 417.68),
(126, 'Lightweight Yoga Mat', 'Lightweight Yoga Mat crafted from bamboo, item #126 in the catalog. Designed for everyday use with a focus on durability and comfort.', 217.78),
(127, 'Insulated Air Purifier', 'Insulated Air Purifier crafted from organic cotton, item #127 in the catalog. Designed for everyday use with a focus on durability and comfort.', 235.16),
(128, 'Industrial Hiking Boots', 'Industrial Hiking Boots crafted from bamboo, item #128 in the catalog. Designed for everyday use with a focus on durability and comfort.', 258.02),
(129, 'Premium Hiking Boots', 'Premium Hiking Boots crafted from recycled polyester, item #129 in the catalog. Designed for everyday use with a focus on durability and comfort.', 145.46),
(130, 'Reinforced Tool Kit', 'Reinforced Tool Kit crafted from recycled polyester, item #130 in the catalog. Designed for everyday use with a focus on durability and comfort.', 410.11),
(131, 'Smart Hiking Boots', 'Smart Hiking Boots crafted from carbon fiber, item #131 in the catalog. Designed for everyday use with a focus on durability and comfort.', 116.19),
(132, 'Eco-Friendly Office Chair', 'Eco-Friendly Office Chair crafted from aluminum, item #132 in the catalog. Designed for everyday use with a focus on durability and comfort.', 27.87),
(133, 'Vintage Air Purifier', 'Vintage Air Purifier crafted from recycled polyester, item #133 in the catalog. Designed for everyday use with a focus on durability and comfort.', 230.42),
(134, 'Insulated Monitor Stand', 'Insulated Monitor Stand crafted from tempered glass, item #134 in the catalog. Designed for everyday use with a focus on durability and comfort.', 249.71),
(135, 'Smart Office Chair', 'Smart Office Chair crafted from aluminum, item #135 in the catalog. Designed for everyday use with a focus on durability and comfort.', 446.86),
(136, 'Ergonomic Cutting Board', 'Ergonomic Cutting Board crafted from tempered glass, item #136 in the catalog. Designed for everyday use with a focus on durability and comfort.', 113.32),
(137, 'Modern Power Bank', 'Modern Power Bank crafted from aluminum, item #137 in the catalog. Designed for everyday use with a focus on durability and comfort.', 280.91),
(138, 'Ergonomic Power Bank', 'Ergonomic Power Bank crafted from stainless steel, item #138 in the catalog. Designed for everyday use with a focus on durability and comfort.', 401.69),
(139, 'Modern Backup Camera', 'Modern Backup Camera crafted from genuine leather, item #139 in the catalog. Designed for everyday use with a focus on durability and comfort.', 162.05),
(140, 'Industrial Air Purifier', 'Industrial Air Purifier crafted from ABS plastic, item #140 in the catalog. Designed for everyday use with a focus on durability and comfort.', 216.23),
(141, 'Modular Power Bank', 'Modular Power Bank crafted from stainless steel, item #141 in the catalog. Designed for everyday use with a focus on durability and comfort.', 373.1),
(142, 'Vintage Power Bank', 'Vintage Power Bank crafted from carbon fiber, item #142 in the catalog. Designed for everyday use with a focus on durability and comfort.', 377.12),
(143, 'Heavy-Duty Cutting Board', 'Heavy-Duty Cutting Board crafted from ABS plastic, item #143 in the catalog. Designed for everyday use with a focus on durability and comfort.', 244.87),
(144, 'Smart Running Shoes', 'Smart Running Shoes crafted from high-density foam, item #144 in the catalog. Designed for everyday use with a focus on durability and comfort.', 43.34),
(145, 'Lightweight Coffee Mug', 'Lightweight Coffee Mug crafted from carbon fiber, item #145 in the catalog. Designed for everyday use with a focus on durability and comfort.', 171.23),
(146, 'Modular Desk Lamp', 'Modular Desk Lamp crafted from stainless steel, item #146 in the catalog. Designed for everyday use with a focus on durability and comfort.', 79.65),
(147, 'Waterproof Sunglasses', 'Waterproof Sunglasses crafted from stainless steel, item #147 in the catalog. Designed for everyday use with a focus on durability and comfort.', 354.67),
(148, 'Wireless Phone Case', 'Wireless Phone Case crafted from tempered glass, item #148 in the catalog. Designed for everyday use with a focus on durability and comfort.', 168.78),
(149, 'Industrial Phone Case', 'Industrial Phone Case crafted from aluminum, item #149 in the catalog. Designed for everyday use with a focus on durability and comfort.', 107.37),
(150, 'Cordless Bike Helmet', 'Cordless Bike Helmet crafted from genuine leather, item #150 in the catalog. Designed for everyday use with a focus on durability and comfort.', 473.29),
(151, 'Rugged Wallet', 'Rugged Wallet crafted from genuine leather, item #151 in the catalog. Designed for everyday use with a focus on durability and comfort.', 193.28),
(152, 'Rugged Camping Tent', 'Rugged Camping Tent crafted from carbon fiber, item #152 in the catalog. Designed for everyday use with a focus on durability and comfort.', 377.96),
(153, 'Cordless Backup Camera', 'Cordless Backup Camera crafted from ABS plastic, item #153 in the catalog. Designed for everyday use with a focus on durability and comfort.', 400.92),
(154, 'Smart Notebook', 'Smart Notebook crafted from bamboo, item #154 in the catalog. Designed for everyday use with a focus on durability and comfort.', 140.09),
(155, 'Vintage Backpack', 'Vintage Backpack crafted from tempered glass, item #155 in the catalog. Designed for everyday use with a focus on durability and comfort.', 171.37),
(156, 'Waterproof Wall Clock', 'Waterproof Wall Clock crafted from stainless steel, item #156 in the catalog. Designed for everyday use with a focus on durability and comfort.', 421.04),
(157, 'Portable Air Purifier', 'Portable Air Purifier crafted from ABS plastic, item #157 in the catalog. Designed for everyday use with a focus on durability and comfort.', 18.34),
(158, 'Waterproof Garden Hose', 'Waterproof Garden Hose crafted from genuine leather, item #158 in the catalog. Designed for everyday use with a focus on durability and comfort.', 333.17),
(159, 'Wireless Sleeping Bag', 'Wireless Sleeping Bag crafted from tempered glass, item #159 in the catalog. Designed for everyday use with a focus on durability and comfort.', 72.16),
(160, 'Industrial Keyboard', 'Industrial Keyboard crafted from aluminum, item #160 in the catalog. Designed for everyday use with a focus on durability and comfort.', 133.77),
(161, 'Adjustable Monitor Stand', 'Adjustable Monitor Stand crafted from high-density foam, item #161 in the catalog. Designed for everyday use with a focus on durability and comfort.', 166.78),
(162, 'Waterproof Running Shoes', 'Waterproof Running Shoes crafted from tempered glass, item #162 in the catalog. Designed for everyday use with a focus on durability and comfort.', 129.86),
(163, 'Wireless Notebook', 'Wireless Notebook crafted from aluminum, item #163 in the catalog. Designed for everyday use with a focus on durability and comfort.', 375.76),
(164, 'Compact Camping Tent', 'Compact Camping Tent crafted from bamboo, item #164 in the catalog. Designed for everyday use with a focus on durability and comfort.', 326.81),
(165, 'Compact Cutting Board', 'Compact Cutting Board crafted from aluminum, item #165 in the catalog. Designed for everyday use with a focus on durability and comfort.', 475.05),
(166, 'Eco-Friendly Umbrella', 'Eco-Friendly Umbrella crafted from aluminum, item #166 in the catalog. Designed for everyday use with a focus on durability and comfort.', 312.55),
(167, 'Smart Office Chair', 'Smart Office Chair crafted from high-density foam, item #167 in the catalog. Designed for everyday use with a focus on durability and comfort.', 336.37),
(168, 'Insulated Monitor Stand', 'Insulated Monitor Stand crafted from high-density foam, item #168 in the catalog. Designed for everyday use with a focus on durability and comfort.', 351.23),
(169, 'Foldable Keyboard', 'Foldable Keyboard crafted from genuine leather, item #169 in the catalog. Designed for everyday use with a focus on durability and comfort.', 305.58),
(170, 'Ergonomic Cutting Board', 'Ergonomic Cutting Board crafted from stainless steel, item #170 in the catalog. Designed for everyday use with a focus on durability and comfort.', 482.53),
(171, 'Ergonomic Garden Hose', 'Ergonomic Garden Hose crafted from aluminum, item #171 in the catalog. Designed for everyday use with a focus on durability and comfort.', 464.79),
(172, 'Insulated Hiking Boots', 'Insulated Hiking Boots crafted from tempered glass, item #172 in the catalog. Designed for everyday use with a focus on durability and comfort.', 201.33),
(173, 'Eco-Friendly Desk Lamp', 'Eco-Friendly Desk Lamp crafted from genuine leather, item #173 in the catalog. Designed for everyday use with a focus on durability and comfort.', 346.84),
(174, 'Smart Bluetooth Speaker', 'Smart Bluetooth Speaker crafted from carbon fiber, item #174 in the catalog. Designed for everyday use with a focus on durability and comfort.', 425.89),
(175, 'Reinforced Blender', 'Reinforced Blender crafted from recycled polyester, item #175 in the catalog. Designed for everyday use with a focus on durability and comfort.', 399.12),
(176, 'Insulated Blender', 'Insulated Blender crafted from aluminum, item #176 in the catalog. Designed for everyday use with a focus on durability and comfort.', 176.86),
(177, 'Cordless Hiking Boots', 'Cordless Hiking Boots crafted from organic cotton, item #177 in the catalog. Designed for everyday use with a focus on durability and comfort.', 39.12),
(178, 'Adjustable Backpack', 'Adjustable Backpack crafted from tempered glass, item #178 in the catalog. Designed for everyday use with a focus on durability and comfort.', 412.04),
(179, 'Ergonomic Phone Case', 'Ergonomic Phone Case crafted from organic cotton, item #179 in the catalog. Designed for everyday use with a focus on durability and comfort.', 319.6),
(180, 'Industrial Sunglasses', 'Industrial Sunglasses crafted from stainless steel, item #180 in the catalog. Designed for everyday use with a focus on durability and comfort.', 220.56),
(181, 'Modern Sleeping Bag', 'Modern Sleeping Bag crafted from carbon fiber, item #181 in the catalog. Designed for everyday use with a focus on durability and comfort.', 309.87),
(182, 'Modular Cutting Board', 'Modular Cutting Board crafted from high-density foam, item #182 in the catalog. Designed for everyday use with a focus on durability and comfort.', 235.1),
(183, 'Insulated Running Shoes', 'Insulated Running Shoes crafted from organic cotton, item #183 in the catalog. Designed for everyday use with a focus on durability and comfort.', 426.59),
(184, 'Wireless Running Shoes', 'Wireless Running Shoes crafted from high-density foam, item #184 in the catalog. Designed for everyday use with a focus on durability and comfort.', 125.7),
(185, 'Industrial Garden Hose', 'Industrial Garden Hose crafted from genuine leather, item #185 in the catalog. Designed for everyday use with a focus on durability and comfort.', 335.74),
(186, 'Adjustable Backpack', 'Adjustable Backpack crafted from high-density foam, item #186 in the catalog. Designed for everyday use with a focus on durability and comfort.', 426.21),
(187, 'Premium Notebook', 'Premium Notebook crafted from bamboo, item #187 in the catalog. Designed for everyday use with a focus on durability and comfort.', 180.63),
(188, 'Heavy-Duty Tool Kit', 'Heavy-Duty Tool Kit crafted from carbon fiber, item #188 in the catalog. Designed for everyday use with a focus on durability and comfort.', 440.75),
(189, 'Heavy-Duty Backup Camera', 'Heavy-Duty Backup Camera crafted from aluminum, item #189 in the catalog. Designed for everyday use with a focus on durability and comfort.', 260.72),
(190, 'Eco-Friendly Desk Lamp', 'Eco-Friendly Desk Lamp crafted from bamboo, item #190 in the catalog. Designed for everyday use with a focus on durability and comfort.', 361.43),
(191, 'Vintage Backup Camera', 'Vintage Backup Camera crafted from bamboo, item #191 in the catalog. Designed for everyday use with a focus on durability and comfort.', 346.84),
(192, 'Vintage Power Bank', 'Vintage Power Bank crafted from aluminum, item #192 in the catalog. Designed for everyday use with a focus on durability and comfort.', 51.05),
(193, 'Smart Bike Helmet', 'Smart Bike Helmet crafted from bamboo, item #193 in the catalog. Designed for everyday use with a focus on durability and comfort.', 156.56),
(194, 'Insulated Camping Tent', 'Insulated Camping Tent crafted from high-density foam, item #194 in the catalog. Designed for everyday use with a focus on durability and comfort.', 278.96),
(195, 'Foldable Phone Case', 'Foldable Phone Case crafted from ABS plastic, item #195 in the catalog. Designed for everyday use with a focus on durability and comfort.', 168.73),
(196, 'Industrial Running Shoes', 'Industrial Running Shoes crafted from carbon fiber, item #196 in the catalog. Designed for everyday use with a focus on durability and comfort.', 129.43),
(197, 'Ergonomic Wall Clock', 'Ergonomic Wall Clock crafted from bamboo, item #197 in the catalog. Designed for everyday use with a focus on durability and comfort.', 161.19),
(198, 'Modular Cutting Board', 'Modular Cutting Board crafted from stainless steel, item #198 in the catalog. Designed for everyday use with a focus on durability and comfort.', 99.8),
(199, 'Vintage Running Shoes', 'Vintage Running Shoes crafted from genuine leather, item #199 in the catalog. Designed for everyday use with a focus on durability and comfort.', 488.41),
(200, 'Modern Air Purifier', 'Modern Air Purifier crafted from carbon fiber, item #200 in the catalog. Designed for everyday use with a focus on durability and comfort.', 490.34)
ON CONFLICT (id) DO NOTHING;
